baseURL = 'https://homework-plug-world.netlify.app/english-2015/'

theme = 'hugo-bearblog'

title = 'HomeWork ʕ•ᴥ•ʔ'
languageCode = 'en-us'

[params]
  description =  "So this is where the homework gets done"
